//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class controltowerEntities : DbContext
    {
        public controltowerEntities()
            : base("name=controltowerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<crew> crew { get; set; }
        public virtual DbSet<employees> employees { get; set; }
        public virtual DbSet<flight> flight { get; set; }
        public virtual DbSet<landingstrips> landingstrips { get; set; }
        public virtual DbSet<passengers> passengers { get; set; }
        public virtual DbSet<plane> plane { get; set; }
        public virtual DbSet<ticket> ticket { get; set; }
    }
}
