//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crew
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public crew()
        {
            this.plane = new HashSet<plane>();
        }
    
        public int CrewID { get; set; }
        public int Pilot { get; set; }
        public int SecondPilot { get; set; }
        public int Stewardess { get; set; }
        public int Engineer { get; set; }
    
        public virtual employees employees { get; set; }
        public virtual employees employees1 { get; set; }
        public virtual employees employees2 { get; set; }
        public virtual employees employees3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plane> plane { get; set; }
    }
}
