//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public int FlightID { get; set; }
        public int Seat { get; set; }
        public int PassengerID { get; set; }
        public decimal TicketID { get; set; }
    
        public virtual flight flight { get; set; }
        public virtual passengers passengers { get; set; }
    }
}
